name: magistracy-01-db-tk-1
services:
  postgres:
    image: postgres:18
    container_name: magistracy-01-db-tk-1-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fadeev
      POSTGRES_PASSWORD: user12345
      POSTGRES_DB: tk1
    volumes:
      - magistracy-01-db-tk-1-pg-data:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - private
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "fadeev",
          "-d",
          "tk1",
        ]
      interval: 2s
      timeout: 3s
      retries: 10

networks:
  private:
    driver: bridge

volumes:
  magistracy-01-db-tk-1-pg-data: